# Generated by Django 6.0.4 on 2026-04-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_items_images_items_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemList',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Category_Name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='Category',
            new_name='category',
        ),
    ]
